### ISSUE TITLE
Add cargo install option to docs

### ISSUE THREAD

**Issue by uncenter** [ckaznable/tenki#10]
I was able to install just fine with `cargo install --git https://github.com/ckaznable/tenki.git`, and that is likely the easiest install method for most people.

**Comment by ckaznable** [comment]
Thanks for the suggestion, I didn't realize that cargo could be installed directly from the git source, and now I've added it.

**Comment by uncenter** [comment]
Yay! I love the project by the way, nice job. ❤️
