### ISSUE TITLE
feat: meteor mode

### ISSUE THREAD

**Issue by ckaznable** [ckaznable/tenki#11]
```
\
 \
  \
   \
    \
     🌟

            •
             •
              •
               ⭐
```

**Comment by fadeevab** [comment]
that's gonna be awesome :) You could use grayscale symbols to be in style: ⋆⭒˚｡⋆★

**Comment by fadeevab** [comment]
@ckaznable Would you consider something like that?
👇 (loading...)
![tenki-stars](https://github.com/ckaznable/tenki/assets/5967447/22d1495b-82f8-4b41-9dde-fe6efb1b354e)

**Comment by ckaznable** [comment]
> @ckaznable Would you consider something like that? 👇

Ya, that's close to what I was thinking, but I've been a little busy lately and couldn't make it happen.

**Comment by fadeevab** [comment]
@ckaznable I will post my PR for what's on my gif, it's a little bit hacky though, cause I had to track the tail, and it doesn't easily fit to the existing code structure.

**Comment by fadeevab** [comment]
PR #12

**Comment by ckaznable** [comment]
Thanks for the PR, but I'd like to restructure the code first. I don't think the current structure is suitable for features expansion, especially in a mode like this one where you need to manage the status of the tail.

**Comment by ckaznable** [comment]
implemented
