### ISSUE TITLE
Feature request for `make install`: try some local ${HOME} directories which don't need `sudo` priviledges

### ISSUE THREAD

**Issue by fadeevab** [ckaznable/tenki#5]
Now, `make install` requires `sudo` to copy the `tenki` binary to `/usr/local/bin`, however, I've got a `~/.local/bin` for user programs (more often `~/bin` is used on Linux).

It makes sense to try copying the binary to one of those directories. It may also require checking the path in the `${PATH}` envvar.

**Workaround:** Copy `target/release/tenki` to your directory of choice.

**Comment by ckaznable** [comment]
I'm deciding between root and non-root users in order to perform different operations in #9

**Comment by ckaznable** [comment]
#9 merged
